//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iskovoe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docement_by_pravonor
    {
        public int id_doc_prav { get; set; }
        public Nullable<int> id_pravonor { get; set; }
        public Nullable<int> id_tip_dop { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<System.DateTime> data_doc { get; set; }
    
        public virtual Pravonor Pravonor { get; set; }
        public virtual Tip_documents Tip_documents { get; set; }
    }
}
