//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iskovoe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iskovoe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Iskovoe()
        {
            this.Pravonor = new HashSet<Pravonor>();
        }
    
        public int id_iskovoe { get; set; }
        public Nullable<int> id_dolg { get; set; }
        public Nullable<int> id_executor { get; set; }
        public Nullable<System.DateTime> data_iscovoe { get; set; }
        public Nullable<byte> status { get; set; }
    
        public virtual Debtors Debtors { get; set; }
        public virtual Executor Executor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pravonor> Pravonor { get; set; }
    }
}
