//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iskovoe.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IskovoeEntities : DbContext
    {
        public IskovoeEntities()
            : base("name=IskovoeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Debtors> Debtors { get; set; }
        public virtual DbSet<Document_by_pravonor> Document_by_pravonor { get; set; }
        public virtual DbSet<Executor> Executor { get; set; }
        public virtual DbSet<Iskovoe> Iskovoe { get; set; }
        public virtual DbSet<Period> Period { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Pravonor> Pravonor { get; set; }
        public virtual DbSet<Sostav> Sostav { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip_documents> Tip_documents { get; set; }
        public virtual DbSet<Tip_forms> Tip_forms { get; set; }
    }
}
